#green
version: "3"
services:
  nuxtjs:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8081:8080"
